---
version: 2
plan:
    project-key: TRUNK
    key: CORE2
    name: OpenMRS Core 2.5.x
    description: Platform 2.5
stages:
    - Build:
          manual: false
          final: false
          jobs:
              - Build
              - Integration Test
    - Deploy:
          manual: false
          final: false
          jobs:
              - Deploy to maven
Build:
    key: BUILD
    tasks:
        - checkout:
            force-clean-build: 'false'
            description: Checkout Default Repository
        - maven:
            executable: Maven 3
            jdk: openjdk-8-jdk
            goal: clean package
            tests: 'true'
            environment: JAVA_HOME=${bamboo.capability.system.jdk.openjdk-8-jdk} MAVEN_OPTS="-Xmx2g"
            description: Build and execute Unit Tests
    artifact-subscriptions: []
Integration Test:
    key: IT
    tasks:
        - maven:
            executable: Maven 3
            jdk: openjdk-8-jdk
            goal: clean test -Pskip-default-test -Pintegration-test
            tests: 'true'
            description: Execute integration tests
    artifact-subscriptions: []
Deploy to maven:
    key: DTM
    tasks:
      - maven:
          executable: Maven 3
          jdk: openjdk-8-jdk
          goal: ${bamboo.mavenDeployGoals}
          description: Deploy to maven repo
    artifact-subscriptions: []

repositories:
    - openmrs-core-2.5.x:
          scope: global
    - Release scripts:
          scope: global
triggers:
    - polling:
          period: '180'
          repositories:
              - openmrs-core-2.5.x
branches:
    create: manually
    delete: never
    link-to-jira: true
notifications:
    - events:
          - plan-failed
      recipients:
          - committers
          - emails:
                - dev@openmrs.org
          - watchers
labels:
    - platform
    - test
dependencies:
    require-all-stages-passing: false
    enabled-for-branches: true
    block-strategy: block_if_parent_has_changes
    plans: []
other:
    concurrent-build-plugin: system-default
---
version: 2
plan:
    key: TRUNK-CORE2
plan-permissions:
    - roles:
          - anonymous
      permissions:
          - view
...
